name: collection_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  json_annotation: ^4.8.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.2
  equatable: ^2.0.7
  connectivity_plus: ^5.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#0B1519"
  image: assets/images/logo4x.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mock/products.json
